# List Comprehensions

Complete the following set of exercises to solidify your knowledge of list comprehensions.

In [3]:
import os

#### 1. Use a list comprehension to create and print a list of consecutive integers starting with 1 and ending with 50.

In [5]:
#your code here

# Create a list of consecutive integers from 1 to 50
consecutive_integers = [i for i in range(1, 51)]
print("Consecutive Integers from 1 to 50:", consecutive_integers)

Consecutive Integers from 1 to 50: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50]


**Explanation:**
- This code generates a list of consecutive integers starting from 1 and ending at 50.
- The `range(1, 51)` function is used to create a sequence of numbers from 1 to 50 (inclusive of 1 and exclusive of 51).
- A **list comprehension** is used to iterate through this range and create a list of these integers.
- The resulting list is stored in the variable `consecutive_integers` and printed.

#### 2. Use a list comprehension to create and print a list of even numbers starting with 2 and ending with 200.

In [8]:
#your code here

# Create a list of even numbers from 2 to 200
even_numbers = [i for i in range(2, 201) if i % 2 == 0]
print(even_numbers)

[2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98, 100, 102, 104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124, 126, 128, 130, 132, 134, 136, 138, 140, 142, 144, 146, 148, 150, 152, 154, 156, 158, 160, 162, 164, 166, 168, 170, 172, 174, 176, 178, 180, 182, 184, 186, 188, 190, 192, 194, 196, 198, 200]


**Explanation:**
- This code generates a list of even numbers starting from 2 and ending at 200.
- The `range(2, 201)` function creates a sequence of numbers from 2 to 200 (inclusive of 2 and exclusive of 201).
- A **list comprehension** is used to iterate through this range, and the condition `if i % 2 == 0` ensures that only even numbers are included in the list.
- The resulting list is stored in the variable `even_numbers` and printed.

In [10]:
#your code here

# Create a list of even numbers from 2 to 200
even_numbers = [i for i in range(2, 201, 2)]
print("Even Numbers from 2 to 200:", even_numbers)

Even Numbers from 2 to 200: [2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98, 100, 102, 104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124, 126, 128, 130, 132, 134, 136, 138, 140, 142, 144, 146, 148, 150, 152, 154, 156, 158, 160, 162, 164, 166, 168, 170, 172, 174, 176, 178, 180, 182, 184, 186, 188, 190, 192, 194, 196, 198, 200]


**Explanation:**
- This code generates a list of even numbers starting from 2 and ending at 200.
- The `range(2, 201, 2)` function creates a sequence of numbers from 2 to 200 (inclusive of 2 and exclusive of 201), with a step of 2. This ensures that only even numbers are included.
- A **list comprehension** is used to create the list directly from the range.
- The resulting list is stored in the variable `even_numbers` and printed with a descriptive label.

#### 3. Use a list comprehension to create and print a list containing all elements of the 10 x 4 array below.

In [13]:
a = [[0.84062117, 0.48006452, 0.7876326 , 0.77109654],
       [0.44409793, 0.09014516, 0.81835917, 0.87645456],
       [0.7066597 , 0.09610873, 0.41247947, 0.57433389],
       [0.29960807, 0.42315023, 0.34452557, 0.4751035 ],
       [0.17003563, 0.46843998, 0.92796258, 0.69814654],
       [0.41290051, 0.19561071, 0.16284783, 0.97016248],
       [0.71725408, 0.87702738, 0.31244595, 0.76615487],
       [0.20754036, 0.57871812, 0.07214068, 0.40356048],
       [0.12149553, 0.53222417, 0.9976855 , 0.12536346],
       [0.80930099, 0.50962849, 0.94555126, 0.33364763]];

**Explanation of the 10x4 Array:**
- The variable `a` is a **10x4 array**, which means it is a list containing 10 sublists (rows), and each sublist contains 4 elements (columns).
- This structure represents a 2-dimensional array (matrix) with 10 rows and 4 columns.
- For example:
  - The first row is `[0.84062117, 0.48006452, 0.7876326, 0.77109654]`.
  - The second row is `[0.44409793, 0.09014516, 0.81835917, 0.87645456]`.
  - This pattern continues for all 10 rows.

In [15]:
#your code here

# Flatten a 10x4 array into a single list
flattened_list = [item for sublist in a for item in sublist]
print("Flattened List:", flattened_list)

Flattened List: [0.84062117, 0.48006452, 0.7876326, 0.77109654, 0.44409793, 0.09014516, 0.81835917, 0.87645456, 0.7066597, 0.09610873, 0.41247947, 0.57433389, 0.29960807, 0.42315023, 0.34452557, 0.4751035, 0.17003563, 0.46843998, 0.92796258, 0.69814654, 0.41290051, 0.19561071, 0.16284783, 0.97016248, 0.71725408, 0.87702738, 0.31244595, 0.76615487, 0.20754036, 0.57871812, 0.07214068, 0.40356048, 0.12149553, 0.53222417, 0.9976855, 0.12536346, 0.80930099, 0.50962849, 0.94555126, 0.33364763]


**Explanation of the Code:**
- This code flattens the **10x4 array** (`a`) into a **single list**.
- The list comprehension `[item for sublist in a for item in sublist]` works as follows:
  - The outer loop (`for sublist in a`) iterates through each row (sublist) in the 2D array.
  - The inner loop (`for item in sublist`) iterates through each element in the current row.
  - Each element is added to the new flattened list.
- The result is a **1-dimensional list** containing all the elements of the original 2D array in row-major order.

#### 4. Add a condition to the list comprehension above so that only values greater than or equal to 0.5 are printed.

In [18]:
#your code here

# Filter values >= 0.5 from the flattened list
filtered_list = [item for sublist in a for item in sublist if item >= 0.5]
print("Filtered List (>= 0.5):", filtered_list)

Filtered List (>= 0.5): [0.84062117, 0.7876326, 0.77109654, 0.81835917, 0.87645456, 0.7066597, 0.57433389, 0.92796258, 0.69814654, 0.97016248, 0.71725408, 0.87702738, 0.76615487, 0.57871812, 0.53222417, 0.9976855, 0.80930099, 0.50962849, 0.94555126]


**Explanation of the Code:**
- This code filters the **flattened list** to include only values that are **greater than or equal to 0.5**.
- The list comprehension `[item for sublist in a for item in sublist if item >= 0.5]` works as follows:
  - The outer loop (`for sublist in a`) iterates through each row (sublist) in the 2D array.
  - The inner loop (`for item in sublist`) iterates through each element in the current row.
  - The condition `if item >= 0.5` ensures that only elements with a value of **0.5 or greater** are included in the new list.
- The result is a **filtered list** containing only the qualifying elements from the original 2D array.

#### 5. Use a list comprehension to create and print a list containing all elements of the 5 x 2 x 3 array below.

In [21]:
b = [[[0.55867166, 0.06210792, 0.08147297],
        [0.82579068, 0.91512478, 0.06833034]],

       [[0.05440634, 0.65857693, 0.30296619],
        [0.06769833, 0.96031863, 0.51293743]],

       [[0.09143215, 0.71893382, 0.45850679],
        [0.58256464, 0.59005654, 0.56266457]],

       [[0.71600294, 0.87392666, 0.11434044],
        [0.8694668 , 0.65669313, 0.10708681]],

       [[0.07529684, 0.46470767, 0.47984544],
        [0.65368638, 0.14901286, 0.23760688]]];

**Explanation of the 5 x 2 x 3 Array:**
- The variable `b` is a **5 x 2 x 3 array**, which means it is a **3-dimensional array** structured as follows:
  - The **outermost dimension** has **5 elements** (e.g., 5 blocks or layers).
  - Each of these 5 elements is a **2 x 3 array** (2 rows and 3 columns).
  - For example:
    - The first block is:
      ```
      [[0.55867166, 0.06210792, 0.08147297],
       [0.82579068, 0.91512478, 0.06833034]]
      ```
    - The second block is:
      ```
      [[0.05440634, 0.65857693, 0.30296619],
       [0.06769833, 0.96031863, 0.51293743]]
      ```
    - This pattern continues for all 5 blocks.
- In total, the array contains **5 x 2 x 3 = 30 elements**.

In [23]:
#your code here

# Flatten a 5x2x3 array into a single list
flattened_list_b = [item for sublist1 in b for sublist2 in sublist1 for item in sublist2]
print("Flattened 5x2x3 List:", flattened_list_b)

Flattened 5x2x3 List: [0.55867166, 0.06210792, 0.08147297, 0.82579068, 0.91512478, 0.06833034, 0.05440634, 0.65857693, 0.30296619, 0.06769833, 0.96031863, 0.51293743, 0.09143215, 0.71893382, 0.45850679, 0.58256464, 0.59005654, 0.56266457, 0.71600294, 0.87392666, 0.11434044, 0.8694668, 0.65669313, 0.10708681, 0.07529684, 0.46470767, 0.47984544, 0.65368638, 0.14901286, 0.23760688]


**Explanation of the Code:**
- This code flattens the **5x2x3 array** (`b`) into a **single 1-dimensional list**.
- The list comprehension `[item for sublist1 in b for sublist2 in sublist1 for item in sublist2]` works as follows:
  - The **outer loop** (`for sublist1 in b`) iterates through each of the **5 blocks** in the outermost dimension.
  - The **middle loop** (`for sublist2 in sublist1`) iterates through each of the **2 rows** within the current block.
  - The **inner loop** (`for item in sublist2`) iterates through each of the **3 elements** in the current row.
  - Each element is added to the new flattened list.
- The result is a **1-dimensional list** containing all **30 elements** of the original 5x2x3 array, in the order they appear.

#### 6. Add a condition to the list comprehension above so that the last value in each subarray is printed, but only if it is less than or equal to 0.5.

In [26]:
#your code here

# Filter the last element of each subarray if it is <= 0.5
filtered_last_elements = [sublist2[-1] for sublist1 in b for sublist2 in sublist1 if sublist2[-1] <= 0.5]
print("Filtered Last Elements (<= 0.5):", filtered_last_elements)

Filtered Last Elements (<= 0.5): [0.08147297, 0.06833034, 0.30296619, 0.45850679, 0.11434044, 0.10708681, 0.47984544, 0.23760688]


**Explanation of the Code:**
- This code filters the **last element** of each subarray in the **5x2x3 array** (`b`) and includes it in a new list **only if it is less than or equal to 0.5**.
- The list comprehension `[sublist2[-1] for sublist1 in b for sublist2 in sublist1 if sublist2[-1] <= 0.5]` works as follows:
  - The **outer loop** (`for sublist1 in b`) iterates through each of the **5 blocks** in the outermost dimension.
  - The **middle loop** (`for sublist2 in sublist1`) iterates through each of the **2 rows** within the current block.
  - The condition `if sublist2[-1] <= 0.5` checks if the **last element** of the current row (`sublist2[-1]`) is less than or equal to 0.5.
  - If the condition is met, the last element is added to the new list.
- The result is a **filtered list** containing only the last elements of each subarray that satisfy the condition.

### Bonus

Try to solve these katas using list comprehensions.

**Easy**
- [Insert values](https://www.codewars.com/kata/invert-values)
- [Sum Square(n)](https://www.codewars.com/kata/square-n-sum)
- [Digitize](https://www.codewars.com/kata/digitize)
- [List filtering](https://www.codewars.com/kata/list-filtering)
- [Arithmetic list](https://www.codewars.com/kata/541da001259d9ca85d000688)

**Medium**
- [Multiples of 3 or 5](https://www.codewars.com/kata/514b92a657cdc65150000006)
- [Count of positives / sum of negatives](https://www.codewars.com/kata/count-of-positives-slash-sum-of-negatives)
- [Categorize new member](https://www.codewars.com/kata/5502c9e7b3216ec63c0001aa)

**Advanced**
- [Queue time counter](https://www.codewars.com/kata/queue-time-counter)

# **Invert values** (easy)

Given a set of numbers, return the additive inverse of each. Each positive becomes negatives, and the negatives become positives.
``` python
[1, 2, 3, 4, 5] --> [-1, -2, -3, -4, -5]
[1, -2, 3, -4, 5] --> [-1, 2, -3, 4, -5]
[] --> []
```

In [32]:
def additive_inverse(numbers):
    return [-num for num in numbers]

if __name__ == "__main__":
    print("Additive inverse [1, 2, 3, 4, 5]:", additive_inverse([1, 2, 3, 4, 5]))
    print("Additive inverse [1, -2, 3, -4, 5]:", additive_inverse([1, -2, 3, -4, 5]))
    print("Additive inverse []:", additive_inverse([]))

Additive inverse [1, 2, 3, 4, 5]: [-1, -2, -3, -4, -5]
Additive inverse [1, -2, 3, -4, 5]: [-1, 2, -3, 4, -5]
Additive inverse []: []


**Explanation of the Code:**
- The function `additive_inverse` takes a list of numbers as input and returns a new list where each number is replaced by its **additive inverse** (i.e., the number with its sign flipped).
- The list comprehension `[-num for num in numbers]` iterates through each number in the input list (`numbers`) and applies the operation `-num` to create the additive inverse.

**What Does `if __name__ == "__main__":` Do?**
- In Python, `__name__` is a special variable that tells you whether the script is being run directly or imported as a module.
  - When you run the script directly, `__name__` is set to `"__main__"`.
  - When the script is imported into another script, `__name__` is set to the name of the module (e.g., the filename without the `.py` extension).
- The `if __name__ == "__main__":` block ensures that the code inside it **only runs when the script is executed directly**, not when it is imported as a module.
  - This is useful for including test code or example usage that should only run when you're testing or running the script directly.

**Example Usage:**
- When you run the script directly, the `print` statements inside the `if __name__ == "__main__":` block will execute:
  - `[1, 2, 3, 4, 5]` becomes `[-1, -2, -3, -4, -5]`.
  - `[1, -2, 3, -4, 5]` becomes `[-1, 2, -3, 4, -5]`.
  - An empty list `[]` remains `[]`.
- If you import this script into another script, the `print` statements will **not run**, and you can safely use the `additive_inverse` function without side effects.

**Key Points:**
- The function works for both positive and negative numbers.
- It handles edge cases, such as an empty list, gracefully.
- Using `if __name__ == "__main__":` makes your code modular and reusable, as it separates the function definition from the example usage or test code.

# **Square(n) Sum** (easy)

Complete the square sum function so that it squares each number passed into it and then sums the results together.

For example, for `[1, 2, 2]` it should return 9 because
$1^2+2^2+2^2=9$.

In [35]:
def square_sum(numbers):
    return sum(num**2 for num in numbers)

if __name__ == "__main__":
    print("Square Sum [1, 2, 2]:", square_sum([1, 2, 2]))
    print("Square Sum [0, 3, 4, 5]:", square_sum([0, 3, 4, 5]))
    print("Square Sum [-1, -2, -3]:", square_sum([-1, -2, -3]))
    print("Square Sum []:", square_sum([]))

Square Sum [1, 2, 2]: 9
Square Sum [0, 3, 4, 5]: 50
Square Sum [-1, -2, -3]: 14
Square Sum []: 0


**Explanation of the Code:**
- The function `square_sum` takes a list of numbers as input and returns the **sum of the squares** of those numbers.
- The expression `num**2 for num in numbers` is a generator expression that calculates the square of each number in the list.
- The `sum()` function adds up all the squared values and returns the result.

**Example Usage:**
- For the list `[1, 2, 2]`, the function calculates `1² + 2² + 2² = 1 + 4 + 4 = 9`.
- For the list `[0, 3, 4, 5]`, the function calculates `0² + 3² + 4² + 5² = 0 + 9 + 16 + 25 = 50`.
- For the list `[-1, -2, -3]`, the function calculates `(-1)² + (-2)² + (-3)² = 1 + 4 + 9 = 14`.

**Key Points:**
- The function works for both positive and negative numbers.
- It handles edge cases, such as an empty list, gracefully (the sum of an empty list is `0`).

# **Digitize** (easy)

Given a non-negative integer, return an array / a list of the individual digits in order.

**Examples:**

``` python
123 => [1,2,3]

1 => [1]

8675309 => [8,6,7,5,3,0,9]
```

In [38]:
def digitize(n):
    return [int(digit) for digit in str(n)]

if __name__ == "__main__":
    print("Digitize 123:", digitize(123))
    print("Digitize 1:", digitize(1))
    print("Digitize 8675309:", digitize(8675309))

Digitize 123: [1, 2, 3]
Digitize 1: [1]
Digitize 8675309: [8, 6, 7, 5, 3, 0, 9]


**Explanation of the Code:**
- The function `digitize` takes a non-negative integer as input and returns a list of its **individual digits**.
- The expression `str(n)` converts the integer `n` into a string, allowing iteration over each character (digit).
- The list comprehension `[int(digit) for digit in str(n)]` converts each character back into an integer and adds it to the list.

**Example Usage:**
- For the number `123`, the function returns `[1, 2, 3]`.
- For the number `1`, the function returns `[1]`.
- For the number `8675309`, the function returns `[8, 6, 7, 5, 3, 0, 9]`.

**Key Points:**
- The function works for any non-negative integer, including `0` (which returns `[0]`).
- It handles large numbers gracefully, as Python supports arbitrarily large integers.

# **List Filtering** (easy)

In this kata you will create a function that takes a list of non-negative integers and strings and returns a new list with the strings filtered out.

**Example**

``` python
filter_list([1,2,'a','b']) == [1,2]
filter_list([1,'a','b',0,15]) == [1,0,15]
filter_list([1,2,'aasf','1','123',123]) == [1,2,123]
```

In [41]:
def filter_list(lst):
    return [item for item in lst if isinstance(item, int)]

if __name__ == "__main__":
    print("Filtered List [1, 2, 'a', 'b']:", filter_list([1, 2, 'a', 'b']))
    print("Filtered List [1, 'a', 'b', 0, 15]:", filter_list([1, 'a', 'b', 0, 15]))
    print("Filtered List [1, 2, 'aasf', '1', '123', 123]:", filter_list([1, 2, 'aasf', '1', '123', 123]))
    print("Filtered List ['a', 'b', 'c']:", filter_list(['a', 'b', 'c']))
    print("Filtered List []:", filter_list([]))

Filtered List [1, 2, 'a', 'b']: [1, 2]
Filtered List [1, 'a', 'b', 0, 15]: [1, 0, 15]
Filtered List [1, 2, 'aasf', '1', '123', 123]: [1, 2, 123]
Filtered List ['a', 'b', 'c']: []
Filtered List []: []


**Explanation of the Code:**
- The function `filter_list` takes a list (`lst`) as input and returns a new list containing only the **integer elements** from the input list.
- The list comprehension `[item for item in lst if isinstance(item, int)]` works as follows:
  - It iterates through each `item` in the input list (`lst`).
  - The `isinstance(item, int)` function checks if the `item` is an integer.
  - Only items that are integers are included in the new list.

**Example Usage:**
- For the list `[1, 2, 'a', 'b']`, the function returns `[1, 2]` (only integers are kept).
- For the list `[1, 'a', 'b', 0, 15]`, the function returns `[1, 0, 15]`.
- For the list `[1, 2, 'aasf', '1', '123', 123]`, the function returns `[1, 2, 123]`.
- For the list `['a', 'b', 'c']`, the function returns `[]` (no integers in the list).
- For an empty list `[]`, the function returns `[]`.

**Key Points:**
- The function filters out all non-integer elements, including strings, floats, and other data types.
- It handles edge cases, such as an empty list, gracefully.

# **Arithmetic List!** (easy)

In this kata, you will write an arithmetic list which is basically a list that contains consecutive terms in the sequence.
You will be given three parameters :

* `first` the first term in the sequence
* `c` the constant that you are going to ADD ( since it is an arithmetic sequence...)
* `l` the number of terms that should be returned

In [44]:
def arithmetic_list(first, c, l):
    return [first + c * i for i in range(l)]

if __name__ == "__main__":
    # Example 1: Generate a sequence starting at 1, adding 2 each step, with 5 terms
    print("Arithmetic List (1, 2, 5):", arithmetic_list(1, 2, 5))
    # Example 2: Generate a sequence starting at 10, subtracting 3 each step, with 4 terms
    print("Arithmetic List (10, -3, 4):", arithmetic_list(10, -3, 4))
    # Example 3: Generate a sequence starting at 0, adding 1 each step, with 10 terms
    print("Arithmetic List (0, 1, 10):", arithmetic_list(0, 1, 10))

Arithmetic List (1, 2, 5): [1, 3, 5, 7, 9]
Arithmetic List (10, -3, 4): [10, 7, 4, 1]
Arithmetic List (0, 1, 10): [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


**Explanation of the Code:**
- The function `arithmetic_list` generates an **arithmetic sequence** (a sequence of numbers where each term increases or decreases by a constant difference).
- It takes three arguments:
  - `first`: The first term of the sequence.
  - `c`: The common difference (the amount added to each term to get the next term).
  - `l`: The number of terms in the sequence.
- The list comprehension `[first + c * i for i in range(l)]` creates the sequence:
  - `i` is the index of the term, starting from `0` and going up to `l-1`.
  - For each `i`, the term is calculated as `first + c * i`.

---

### **Concrete Example: `arithmetic_list(1, 2, 5)`**
Let’s break down how the function works for this specific example:

1. **Arguments Passed:**
   - `first = 1`: The first term of the sequence is `1`.
   - `c = 2`: The common difference is `2` (each term increases by `2`).
   - `l = 5`: The sequence will have `5` terms.

2. **List Comprehension Execution:**
   - The loop `for i in range(l)` will iterate over `i = 0, 1, 2, 3, 4` (since `range(5)` produces `[0, 1, 2, 3, 4]`).
   - For each `i`, the term is calculated as `first + c * i`:
     - When `i = 0`: `1 + 2 * 0 = 1`
     - When `i = 1`: `1 + 2 * 1 = 3`
     - When `i = 2`: `1 + 2 * 2 = 5`
     - When `i = 3`: `1 + 2 * 3 = 7`
     - When `i = 4`: `1 + 2 * 4 = 9`

3. **Resulting List:**
   - The list comprehension collects these terms into a list: `[1, 3, 5, 7, 9]`.

---

**Key Points:**
- The function can generate both increasing and decreasing sequences, depending on the value of `c`.
- It handles edge cases, such as `l = 0`, gracefully (returns an empty list).
- The sequence is generated efficiently using a list comprehension.

# **Multiples of 3 or 5** (medium)

If we list all the natural numbers below `10` that are multiples of `3` or `5`, we get `3`, `5`, `6` and `9`. The sum of these multiples is `23`.

Finish the solution so that it returns the sum of all the multiples of `3` or `5` below the number passed in.

Additionally, if the number is negative, return `0`.

Note: If the number is a multiple of both `3` and `5`, only count it once.

In [73]:
def sum_of_multiples(n):
    return sum(x for x in range(1, n) if x % 3 == 0 or x % 5 == 0) if n > 0 else 0

if __name__ == "__main__":
    print("Sum of Multiples (10):", sum_of_multiples(10))
    print("Sum of Multiples (20):", sum_of_multiples(20))
    print("Sum of Multiples (-5):", sum_of_multiples(-5))
    print("Sum of Multiples (0):", sum_of_multiples(0))  # Added test case for 0

Sum of Multiples (10): 23
Sum of Multiples (20): 78
Sum of Multiples (-5): 0
Sum of Multiples (0): 0


**Explanation of the Code:**
- The function `sum_of_multiples` calculates the sum of all **natural numbers below `n`** that are multiples of `3` or `5`.
- It uses a **generator expression** inside the `sum()` function to iterate through all numbers from `1` to `n-1` (`range(1, n)`).
- The condition `if x % 3 == 0 or x % 5 == 0` ensures that only numbers divisible by `3` or `5` are included in the sum.
- If `n` is less than or equal to `0`, the function returns `0` (as specified in the problem).

**Example Usage:**
1. **For `n = 10`:**
   - Natural numbers below `10` are `[1, 2, 3, 4, 5, 6, 7, 8, 9]`.
   - Multiples of `3` or `5` are `[3, 5, 6, 9]`.
   - Their sum is `3 + 5 + 6 + 9 = 23`.
   - Output: `23`.
2. **For `n = 20`:**
   - Natural numbers below `20` are `[1, 2, 3, ..., 19]`.
   - Multiples of `3` or `5` are `[3, 5, 6, 9, 10, 12, 15, 18]`.
   - Their sum is `3 + 5 + 6 + 9 + 10 + 12 + 15 + 18 = 78`.
   - Output: `78`.
3. **For `n = -5`:**
   - Since `n` is negative, the function returns `0`.
   - Output: `0`.
4. **For `n = 0`:**
   - Since `n` is `0`, there are no natural numbers below `0`, so the function returns `0`.
   - Output: `0`.

**Key Points:**
- The function handles edge cases, such as negative numbers and `0`, gracefully.
- It ensures that numbers divisible by both `3` and `5` (e.g., `15`) are counted only once.
- The use of a generator expression makes the code concise and efficient.
- The range starts from `1` to exclude `0`, as `0` is not a natural number.

# **Count of positives / sum of negatives** (medium)

Given an array of integers.

Return an array, where the first element is the count of positives numbers and the second element is sum of negative numbers. 0 is neither positive nor negative.

If the input is an empty array or is null, return an empty array.

**Example**

For input `[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, -11, -12, -13, -14, -15]`, you should return `[10, -65]`.

In [86]:
def count_positives_sum_negatives(arr):
    # Check if the input array is empty or null
    if arr is None or not arr:
        return []

    # Initialize counters for positive and the sum of negative numbers
    count_positives = 0
    sum_negatives = 0

    # Iterate through each element in the array
    for num in arr:
        if num > 0:
            count_positives += 1
        elif num < 0:
            sum_negatives += num

    # Return a list containing the count of positive numbers and the sum of negative numbers
    return [count_positives, sum_negatives]

if __name__ == "__main__":
    # Test cases
    input1 = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, -11, -12, -13, -14, -15]
    input2 = []
    input3 = None

    result1 = count_positives_sum_negatives(input1)
    result2 = count_positives_sum_negatives(input2)
    result3 = count_positives_sum_negatives(input3)

    # Print results with input arrays
    print(f"Input: {input1} -> Result: {result1}")
    print(f"Input: {input2} -> Result: {result2}")
    print(f"Input: {input3} -> Result: {result3}")

Input: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, -11, -12, -13, -14, -15] -> Result: [10, -65]
Input: [] -> Result: []
Input: None -> Result: []


**Explanation of the Code:**
- The function `count_positives_sum_negatives` takes an array of integers as input and returns a list where:
  - The **first element** is the count of positive numbers.
  - The **second element** is the sum of negative numbers.
- The function handles edge cases:
  - If the input array is `None` or empty, it returns an empty list.
- The function iterates through each number in the array:
  - If the number is greater than `0`, it increments the `count_positives` counter.
  - If the number is less than `0`, it adds the number to `sum_negatives`.
- The result is a list containing `[count_positives, sum_negatives]`.

**Example Usage:**
1. **For input `[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, -11, -12, -13, -14, -15]`:**
   - Positive numbers: `[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]` → Count: `10`.
   - Negative numbers: `[-11, -12, -13, -14, -15]` → Sum: `-65`.
   - Output: `[10, -65]`.
2. **For input `[]`:**
   - The array is empty, so the function returns an empty list.
   - Output: `[]`.
3. **For input `None`:**
   - The input is `None`, so the function returns an empty list.
   - Output: `[]`.

**Key Points:**
- The function handles `None` and empty arrays gracefully.
- It correctly identifies positive and negative numbers, ignoring `0` (as `0` is neither positive nor negative).
- The use of a loop and conditional checks ensures the function works efficiently.

# **Categorize New Member** (medium)

The Western Suburbs Croquet Club has two categories of membership, Senior and Open. They would like your help with an application form that will tell prospective members which category they will be placed.

To be a senior, a member must be at least `55` years old and have a handicap greater than `7`. In this croquet club, handicaps range from `-2` to `+26`; the better the player the lower the handicap.

**Input**

Input will consist of a list of pairs. Each pair contains information for a single potential member. Information consists of an integer for the person's age and an integer for the person's handicap.

**Output**

Output will consist of a list of string values (in Haskell and C: `Open` or `Senior`) stating whether the respective member is to be placed in the senior or open category.

**Example**
``` python
input =  [[18, 20], [45, 2], [61, 12], [37, 6], [21, 21], [78, 9]]
output = ["Open", "Open", "Senior", "Open", "Open", "Senior"]
```

In [92]:
def categorize_members(data):
    # Validate input: ensure data is a list of pairs
    if not isinstance(data, list) or not all(isinstance(member, list) and len(member) == 2 for member in data):
        raise ValueError("Input must be a list of pairs [age, handicap].")

    # For each member in the input list, categorize them as 'Senior' or 'Open'
    return [
        "Senior" if age >= 55 and handicap > 7 else "Open"
        for age, handicap in data
    ]

if __name__ == "__main__":
    # Example usage
    input_data = [[18, 20], [45, 2], [61, 12], [37, 6], [21, 21], [78, 9]]
    result = categorize_members(input_data)

    # Print input and output for clarity
    print("Input Data:", input_data)
    print("Categorized Members:", result)

Input Data: [[18, 20], [45, 2], [61, 12], [37, 6], [21, 21], [78, 9]]
Categorized Members: ['Open', 'Open', 'Senior', 'Open', 'Open', 'Senior']


**Explanation of the Code:**
- The function `categorize_members` takes a list of pairs as input, where each pair contains the `age` and `handicap` of a potential member.
- It categorizes each member as either **"Senior"** or **"Open"** based on the following rules:
  - A member is **"Senior"** if they are **at least 55 years old** and have a **handicap greater than 7**.
  - Otherwise, the member is **"Open"**.
- The function uses a **list comprehension** to iterate through the input data and apply the categorization logic.

**Input Validation:**
- The function checks if the input is valid before processing it:
  - `if not isinstance(data, list)`: This checks if the input `data` is a **list**. If not, the input is invalid.
  - `or not all(isinstance(member, list) and len(member) == 2 for member in data)`: This checks if every element in `data` is a **pair** (a list with exactly two elements: `[age, handicap]`).
    - `isinstance(member, list)`: Ensures each element in `data` is a list.
    - `len(member) == 2`: Ensures each list has exactly two elements.
  - If the input fails either of these checks, the function raises a `ValueError` with the message: `"Input must be a list of pairs [age, handicap]."`

**Example Usage:**
- For the input `[[18, 20], [45, 2], [61, 12], [37, 6], [21, 21], [78, 9]]`:
  - `[18, 20]`: Age < 55 → "Open"
  - `[45, 2]`: Age < 55 → "Open"
  - `[61, 12]`: Age >= 55 and handicap > 7 → "Senior"
  - `[37, 6]`: Age < 55 → "Open"
  - `[21, 21]`: Age < 55 → "Open"
  - `[78, 9]`: Age >= 55 and handicap > 7 → "Senior"
- The output is: `["Open", "Open", "Senior", "Open", "Open", "Senior"]`.

**Key Points:**
- The function handles the categorization logic efficiently using a list comprehension.
- It includes input validation to ensure the input is in the correct format.
- The output is a list of strings indicating the category for each member.

# **Queue time counter** (advanced)

You managed to send your friend to queue for tickets in your stead, but there is a catch: he will get there only if you tell him how much that is going to take. And everybody can only take one ticket at a time, then they go back in the last position of the queue if they need more (or go home if they are fine).

Each ticket takes one minutes to emit, the queue is well disciplined, Brit-style, and so it moves smoothly, with no waste of time.

You will be given an array/list/vector with all the people queuing and the initial position of your buddy, so for example, knowing that your friend is in the third position (that we will consider equal to the index, 2 (3 in COBOL): he is the guy that wants 3 tickets!) and the initial queue is `[2, 5, 3, 4, 6]`.

The first dude gets his ticket and the queue goes now like this `[5, 3, 4, 6, 1]`, then `[3, 4, 6, 1, 4]` and so on. In the end, our buddy will be queuing for 12 minutes, true story!

Build a function to compute it, resting assured that only positive integers are going to be there and you will be always given a valid index; but we also want to go to pretty popular events, so be ready for big queues with people getting plenty of tickets.

In [110]:
def queue_time_counter(queue, position):
    time = 0  # Initialize a counter for time

    print(f"Initial Queue: {queue}")
    print(f"Target Position: {position} (0-based index)")
    print("---")

    while True:  # Loop until the target person is done
        time += 1  # One minute passes as a ticket is issued
        print(f"Minute {time}:")
        print(f"  Queue before processing: {queue}")
        print(f"  Target Position: {position}")

        # Reduce the tickets needed for the first person
        queue[0] -= 1
        print(f"  First person takes a ticket. Tickets left for them: {queue[0]}")

        # Check if the target person has received their last ticket
        if position == 0 and queue[0] == 0:
            print(f"  Target person is done! Total time: {time} minutes")
            break

        # Rotate the queue if the first person still needs tickets
        if queue[0] > 0:
            print(f"  First person still needs tickets. Moving them to the end of the queue.")
            queue.append(queue.pop(0))
        else:
            print(f"  First person is done. Removing them from the queue.")
            queue.pop(0)  # Remove the person if they are done

        # Update the position of the target person
        position = position - 1 if position > 0 else len(queue) - 1
        print(f"  Updated Target Position: {position}")
        print(f"  Queue after processing: {queue}")
        print("---")

    return time

if __name__ == "__main__":
    # Example usage
    queue = [2, 5, 3, 4, 6]
    position = 2

    result = queue_time_counter(queue, position)
    print("\nFinal Result:")
    print(f"Total time for target person to get all tickets: {result} minutes")

Initial Queue: [2, 5, 3, 4, 6]
Target Position: 2 (0-based index)
---
Minute 1:
  Queue before processing: [2, 5, 3, 4, 6]
  Target Position: 2
  First person takes a ticket. Tickets left for them: 1
  First person still needs tickets. Moving them to the end of the queue.
  Updated Target Position: 1
  Queue after processing: [5, 3, 4, 6, 1]
---
Minute 2:
  Queue before processing: [5, 3, 4, 6, 1]
  Target Position: 1
  First person takes a ticket. Tickets left for them: 4
  First person still needs tickets. Moving them to the end of the queue.
  Updated Target Position: 0
  Queue after processing: [3, 4, 6, 1, 4]
---
Minute 3:
  Queue before processing: [3, 4, 6, 1, 4]
  Target Position: 0
  First person takes a ticket. Tickets left for them: 2
  First person still needs tickets. Moving them to the end of the queue.
  Updated Target Position: 4
  Queue after processing: [4, 6, 1, 4, 2]
---
Minute 4:
  Queue before processing: [4, 6, 1, 4, 2]
  Target Position: 4
  First person takes a

**Explanation of the Code:**
- The function `queue_time_counter` calculates the total time it takes for a specific person in a queue to get all their tickets.
- The queue is represented as a list of integers, where each integer is the number of tickets a person needs.
- The `position` parameter indicates the initial position of the target person in the queue (0-based index).

**How It Works:**
1. **Initialization:**
   - `time` is initialized to `0` to keep track of the total time elapsed.
2. **Processing the Queue:**
   - For each minute (`time += 1`), the first person in the queue gets one ticket (`queue[0] -= 1`).
   - If the first person is the target (`position == 0`) and they have no more tickets to get (`queue[0] == 0`), the loop breaks, and the total time is returned.
3. **Rotating the Queue:**
   - If the first person still needs more tickets (`queue[0] > 0`), they are moved to the end of the queue (`queue.append(queue.pop(0))`).
   - If the first person is done (`queue[0] == 0`), they are removed from the queue (`queue.pop(0)`).
4. **Updating the Target Position:**
   - If the target person is not at the front of the queue, their position is updated (`position = position - 1 if position > 0 else len(queue) - 1`).

**Example Usage:**
- For the queue `[2, 5, 3, 4, 6]` and target position `2`:
  - The target person needs `3` tickets and is initially in the 3rd position (index `2`).
  - The function simulates the queue process and returns the total time taken for the target person to get all their tickets.
  - Output: `12`.

**Key Points:**
- The function handles the queue rotation and ticket distribution efficiently.
- It ensures the target person's position is updated correctly as the queue changes.
- The loop continues until the target person receives all their tickets.